(function(b){"function"===typeof define&&define.amd?define("xmltree",["jquery"],b):window.XMLTree=b(window.jQuery)})(function(b){function y(a){window.DOMParser?(parser=new DOMParser,xmlDoc=parser.parseFromString(a,"text/xml")):(xmlDoc=new ActiveXObject("Microsoft.XMLDOM"),xmlDoc.async=!1,xmlDoc.loadXML(a));return xmlDoc}function v(a){var l=[];a.parents("li").andSelf().each(function(){var a=b(this).children(".LIText").children(".tree_node").text(),k=a;if(0!=b(this).siblings().filter(function(){return b(this).children(".LIText").children(".tree_node").text()==
a}).length)var f=b(this).prevAll().filter(function(){return b(this).children(".LIText").children(".tree_node").text()==a}).length+1,k=k+("["+f+"]");l.push(k)});return"/"+l.join("/")}function q(){if(window.console&&console.log&&z)for(var a in arguments)console.log(arguments[a])}function w(a,b,g){function k(a,b){a=a.replace(/[^\w\-_]/g,"-").replace(/-{2,}/g,"-").replace(/^[^a-z]/,function(a){return"node-"+a});var c=Array(g+2).join("\t"),f;f="\n"+c+"<"+a+">\n"+c+"\t"+("object"!=typeof b?b:w(b,null,g+
1));return f+"\n"+c+"</"+a+">\n"}var f="";g=g||0;b=b||"root";g||(f="<"+b+">");if("[object Object]"==a.toString())for(var h in a)f+=k(h,a[h]);else if(a instanceof Array){h=0;for(var p=a.length;h<p;h++)f+=k("node",a[h])}g||(f+="</"+b+">");return f.replace(/&(?= )/g,"&amp;").replace(/^\n(?=<)/,"").replace(/\n{2,}/g,"\n").replace(/^\t+\n/mg,"")}var z=-1!=location.href.indexOf("XMLTreeLog=true");XMLTree=function(a,l){function g(){var c=this;this.xml=b("string"==typeof this.xml?y(this.xml):this.xml);l&&
(this.xml=this.xml.children(":first"));a.XMLCallback&&(this.xml=a.XMLCallback(this.xml));q("XML fed to XMLTree:",this.xml);if(a.openAtPath){var g=this.xml.find(a.openAtPath);1==g.length&&g.attr("currSel","true")}this.xml.children().each(function(){k(b(this),c.tree)});l&&(this.xml.children().length?this.tree.show():this.tree.prev(".plusMin").andSelf().remove());f.call(this)}function k(c,f){var g,m,r,e,d,t,u;g=c[0].tagName;f.append(m=b("<li>").addClass(g).append(u=b("<span>").addClass("LIText")).append(r=
b("<ul>")));m.append(b("<span>",{html:a.startExpanded?"-":"+"}).addClass("plusMin expanded"));e=c[0].attributes;if(a.attrsAsClasses)for(d=0;d<e.length;d++)(!0===a.attrsAsClasses||"string"==typeof a.attrsAsClasses&&a.attrsAsClasses==e[d].name||a.attrsAsClasses instanceof Array&&-1!=b.inArray(e[d].name,a.attrsAsClasses))&&m.addClass(e[d].name+"-"+e[d].value+" "+e[d].name);if(a.attrsAsData)for(d=0;d<e.length;d++)(!0===a.attrsAsData||"string"==typeof a.attrsAsData&&a.attrsAsData==e[d].name||a.attrsAsData instanceof
Array&&-1!=b.inArray(e[d].name,a.attrsAsData))&&m.attr("data-"+e[d].name,e[d].value);if(a.attrs&&"ignore"==a.attrs)e=!1;else if(e)for(d=0;d<e.length;d++)e[d].value&&(r.append(h=b("<li>").append(b("<span>",{text:e[d].value}).addClass("attrValue")).addClass("attr "+e[d].name).prepend(b("<span>",{text:"@"+e[d].name+":"}))),a.attrs&&"hidden"==a.attrs&&h.hide());d=c.children();!d.length&&(!e.length||e.length&&a.attrs&&"hidden"==a.attrs)&&m.addClass("noKids");g=b("<span>",{text:g}).addClass("tree_node");
d.length?(u.prepend(c.immediateText()+(a.noDots?"":"..")).prepend(g),t=function(d,e){return function(){d.each(function(){k(b(this),e)});a.renderCallback&&a.renderCallback(e,this,l)}}(d,r),a.startExpanded||a.subTreeBranches?t():m.children(".plusMin").bind("click.sp",function(){t();b(this).unbind("click.sp")})):u.prepend(c.immediateText()).prepend(g)}function f(){a.subTreeBranches&&(!0===a.subTreeBranches?this.tree.addClass("subTreeRequestsOnAllNodes"):this.tree.find(a.subTreeBranches).addClass("subTreeNode"));
this.tree.on("click",".plusMin",function(e){e.stopPropagation();var d=b(this).parent().children("ul"),c=b(this).is(".collapsed")?"closed":"open",g=v(b(this).parent()),f=b(this).parent();d["closed"==c?"show":"hide"]();a.plusMinCallback&&a.plusMinCallback(f,g,e,c);a.subTreeBranches&&(!0===a.subTreeBranches||b(this).parent().is(".subTreeNode"))&&a.subTreeRequest&&"closed"==c&&!f.data("subTreeDataFetched")&&(e=a.subTreeRequest(f,g,e,c))&&"string"==typeof e&&new XMLTree(b.extend(a,{fpath:e,container:f}),
!0)&&f.data("subTreeDataFetched",!0);b(this).html("closed"==c?"-":"+").removeClass("expanded collapsed").addClass("closed"==c?"expanded":"collapsed");if(!a.noURLTracking){var k=[];n.tree.find("ul:visible").filter(function(){return!b(this).find("ul:visible").length}).each(function(){var a=[];b(this).parents("li").each(function(){a.unshift(b(this).index())});k.push(a.join(","))});var h="tree"+n.instanceID+":"+k.join("|")+";",l=!1,c=location.hash.replace(new RegExp("tree"+n.instanceID+":([0-9,-|]+);"),
function(a){l=!0;return h});l||(c=-1!==c.indexOf(";",c.length-1)?c+h:c+";"+h);location.hash=c}});if(a.clickCallback)this.tree.on("click",".LIText",function(c){var d=b(this).closest("li");a.clickCallback(d,v(d),c)});a.hideAttrs&&!a.subTree&&this.tree.addClass("hideAttrs");a.hideNodeNames&&!a.subTree&&this.tree.addClass("hideNodeNames");a.renderCallback&&a.renderCallback(this.tree,this,l);var c=(new RegExp("tree"+this.instanceID+":([0-9,-|]+);")).exec(location.hash);if(c){var c=c[1].split("|"),g;for(g in c){var f=
c[g].split(","),k=[],h;for(h in f)k.push("li:eq("+f[h]+") > ul");this.tree.find(k.join(" > ")).parents("ul").andSelf().show().each(function(){b(this).parent().children(".plusMin").html("-")})}}else this.tree.find(".currSel").parentsUntil(".xmltree").show()}-1!=location.href.indexOf("debug")&&(this.debug=!0);if(!(this instanceof XMLTree))q("XMLTree was called but not instantiated");else if(a.fpath||a.xml){if(a.container&&b(a.container).length||a.justReturn){var h,p=b(a.container),n=this;this.tree=
l?p.children("ul").hide():b("<ul>");this.instanceID=XMLTree.instancesCounter;this.tree.attr("id","tree_"+this.instanceID);XMLTree.instancesCounter++;l||(this.tree.addClass("xmltree"),a["class"]&&this.tree.addClass(a["class"]),a.startExpanded&&this.tree.addClass("startExpanded"));if(a.data)for(var x in a.data)this.tree.data(x,a.data[x]);l&&this.tree.addClass("forcePlusMin");a.justReturn||this.tree.appendTo(p);a.fpath?(q("XML tree fpath:",a.fpath),b.ajax({url:a.fpath,cache:void 0==a.cache?!0:a.cache,
dataType:a.jsonp?"jsonp":a.json?"json":"xml"}).done(function(b){if(a.json)return a.jsonCallback&&(b=a.jsonCallback(b)),delete a.fpath,a.xml=w(b),new XMLTree(a,l);b=b.replace(/<\?xml[^>]+>\s*/,"");n.xml=b;g.call(n,b)}).error(function(){alert("XMLTree error - could not load XML from "+a.fpath)})):"string"==typeof a.xml?(this.xml=a.xml.replace(/<\?xml[^>]+>\s*/,""),g.call(this)):alert("XMLTree error - jdo.xml is not a string");return this.tree}alert("XMLTree error - No container selector passed or does not match element in DOM")}};
XMLTree.instancesCounter=0;b.fn.immediateText=function(){return b(this).clone().children().remove().end().text()};return XMLTree});